// Code generated by protoc-gen-go.
// source: golang.conradwood.net/apis/promconfig/promconfig.proto
// DO NOT EDIT!

/*
Package promconfig is a generated protocol buffer package.

It is generated from these files:
	golang.conradwood.net/apis/promconfig/promconfig.proto

It has these top-level messages:
	Target
	Reporter
	TargetList
	PercentAlert
	SeriesMatch
	Series
	SeriesList
	PercentAlertList
	Config
	TargetConfig
*/
package promconfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"
import htmlserver "golang.conradwood.net/apis/htmlserver"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlertEffects int32

const (
	AlertEffects_NOBODY AlertEffects = 0
	AlertEffects_USERS  AlertEffects = 1
	AlertEffects_SYSOP  AlertEffects = 2
)

var AlertEffects_name = map[int32]string{
	0: "NOBODY",
	1: "USERS",
	2: "SYSOP",
}
var AlertEffects_value = map[string]int32{
	"NOBODY": 0,
	"USERS":  1,
	"SYSOP":  2,
}

func (x AlertEffects) String() string {
	return proto.EnumName(AlertEffects_name, int32(x))
}
func (AlertEffects) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Target struct {
	Name      string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Addresses []string  `protobuf:"bytes,2,rep,name=Addresses" json:"Addresses,omitempty"`
	Reporter  *Reporter `protobuf:"bytes,3,opt,name=Reporter" json:"Reporter,omitempty"`
	HTTPOnly  bool      `protobuf:"varint,4,opt,name=HTTPOnly" json:"HTTPOnly,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Target) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *Target) GetHTTPOnly() bool {
	if m != nil {
		return m.HTTPOnly
	}
	return false
}

type Reporter struct {
	Reporter string `protobuf:"bytes,1,opt,name=Reporter" json:"Reporter,omitempty"`
}

func (m *Reporter) Reset()                    { *m = Reporter{} }
func (m *Reporter) String() string            { return proto.CompactTextString(m) }
func (*Reporter) ProtoMessage()               {}
func (*Reporter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reporter) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

type TargetList struct {
	Reporter *Reporter `protobuf:"bytes,1,opt,name=Reporter" json:"Reporter,omitempty"`
	Targets  []*Target `protobuf:"bytes,2,rep,name=Targets" json:"Targets,omitempty"`
}

func (m *TargetList) Reset()                    { *m = TargetList{} }
func (m *TargetList) String() string            { return proto.CompactTextString(m) }
func (*TargetList) ProtoMessage()               {}
func (*TargetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TargetList) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *TargetList) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type PercentAlert struct {
	ID          uint64       `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TotalMetric string       `protobuf:"bytes,2,opt,name=TotalMetric" json:"TotalMetric,omitempty"`
	CountMetric string       `protobuf:"bytes,3,opt,name=CountMetric" json:"CountMetric,omitempty"`
	Effects     AlertEffects `protobuf:"varint,4,opt,name=Effects,enum=promconfig.AlertEffects" json:"Effects,omitempty"`
}

func (m *PercentAlert) Reset()                    { *m = PercentAlert{} }
func (m *PercentAlert) String() string            { return proto.CompactTextString(m) }
func (*PercentAlert) ProtoMessage()               {}
func (*PercentAlert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PercentAlert) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PercentAlert) GetTotalMetric() string {
	if m != nil {
		return m.TotalMetric
	}
	return ""
}

func (m *PercentAlert) GetCountMetric() string {
	if m != nil {
		return m.CountMetric
	}
	return ""
}

func (m *PercentAlert) GetEffects() AlertEffects {
	if m != nil {
		return m.Effects
	}
	return AlertEffects_NOBODY
}

type SeriesMatch struct {
	Prefix       []string `protobuf:"bytes,1,rep,name=Prefix" json:"Prefix,omitempty"`
	PartialMatch bool     `protobuf:"varint,2,opt,name=PartialMatch" json:"PartialMatch,omitempty"`
}

func (m *SeriesMatch) Reset()                    { *m = SeriesMatch{} }
func (m *SeriesMatch) String() string            { return proto.CompactTextString(m) }
func (*SeriesMatch) ProtoMessage()               {}
func (*SeriesMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SeriesMatch) GetPrefix() []string {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SeriesMatch) GetPartialMatch() bool {
	if m != nil {
		return m.PartialMatch
	}
	return false
}

type Series struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *Series) Reset()                    { *m = Series{} }
func (m *Series) String() string            { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()               {}
func (*Series) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Series) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SeriesList struct {
	Series []*Series `protobuf:"bytes,1,rep,name=Series" json:"Series,omitempty"`
}

func (m *SeriesList) Reset()                    { *m = SeriesList{} }
func (m *SeriesList) String() string            { return proto.CompactTextString(m) }
func (*SeriesList) ProtoMessage()               {}
func (*SeriesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SeriesList) GetSeries() []*Series {
	if m != nil {
		return m.Series
	}
	return nil
}

type PercentAlertList struct {
	Alerts []*PercentAlert `protobuf:"bytes,1,rep,name=Alerts" json:"Alerts,omitempty"`
}

func (m *PercentAlertList) Reset()                    { *m = PercentAlertList{} }
func (m *PercentAlertList) String() string            { return proto.CompactTextString(m) }
func (*PercentAlertList) ProtoMessage()               {}
func (*PercentAlertList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PercentAlertList) GetAlerts() []*PercentAlert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type Config struct {
	Configs []*TargetConfig `protobuf:"bytes,1,rep,name=Configs" json:"Configs,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Config) GetConfigs() []*TargetConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

type TargetConfig struct {
	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName" json:"ServiceName,omitempty"`
	SampleLimit uint32 `protobuf:"varint,2,opt,name=SampleLimit" json:"SampleLimit,omitempty"`
}

func (m *TargetConfig) Reset()                    { *m = TargetConfig{} }
func (m *TargetConfig) String() string            { return proto.CompactTextString(m) }
func (*TargetConfig) ProtoMessage()               {}
func (*TargetConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TargetConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *TargetConfig) GetSampleLimit() uint32 {
	if m != nil {
		return m.SampleLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Target)(nil), "promconfig.Target")
	proto.RegisterType((*Reporter)(nil), "promconfig.Reporter")
	proto.RegisterType((*TargetList)(nil), "promconfig.TargetList")
	proto.RegisterType((*PercentAlert)(nil), "promconfig.PercentAlert")
	proto.RegisterType((*SeriesMatch)(nil), "promconfig.SeriesMatch")
	proto.RegisterType((*Series)(nil), "promconfig.Series")
	proto.RegisterType((*SeriesList)(nil), "promconfig.SeriesList")
	proto.RegisterType((*PercentAlertList)(nil), "promconfig.PercentAlertList")
	proto.RegisterType((*Config)(nil), "promconfig.Config")
	proto.RegisterType((*TargetConfig)(nil), "promconfig.TargetConfig")
	proto.RegisterEnum("promconfig.AlertEffects", AlertEffects_name, AlertEffects_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PromConfigService service

type PromConfigServiceClient interface {
	// query registry for new targets
	QueryForTargets(ctx context.Context, in *Reporter, opts ...grpc.CallOption) (*TargetList, error)
	// submit new targes, call this when we want to replace a bunch of new targets
	NewTargets(ctx context.Context, in *TargetList, opts ...grpc.CallOption) (*common.Void, error)
	// find series by partial name match
	FindSeries(ctx context.Context, in *SeriesMatch, opts ...grpc.CallOption) (*SeriesList, error)
	// get a list of all metrics
	GetSeries(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*SeriesList, error)
	// save or create a simple percentage-based alert. If ID is set it will overwrite existing one
	UpdatePercentageAlert(ctx context.Context, in *PercentAlert, opts ...grpc.CallOption) (*PercentAlert, error)
	// get all percentage alert
	GetAllPercentageAlerts(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PercentAlertList, error)
	// renderer/editor
	HTMLRenderer(ctx context.Context, in *htmlserver.SnippetRequest, opts ...grpc.CallOption) (*htmlserver.SnippetResponse, error)
}

type promConfigServiceClient struct {
	cc *grpc.ClientConn
}

func NewPromConfigServiceClient(cc *grpc.ClientConn) PromConfigServiceClient {
	return &promConfigServiceClient{cc}
}

func (c *promConfigServiceClient) QueryForTargets(ctx context.Context, in *Reporter, opts ...grpc.CallOption) (*TargetList, error) {
	out := new(TargetList)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/QueryForTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) NewTargets(ctx context.Context, in *TargetList, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/NewTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) FindSeries(ctx context.Context, in *SeriesMatch, opts ...grpc.CallOption) (*SeriesList, error) {
	out := new(SeriesList)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/FindSeries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) GetSeries(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*SeriesList, error) {
	out := new(SeriesList)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/GetSeries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) UpdatePercentageAlert(ctx context.Context, in *PercentAlert, opts ...grpc.CallOption) (*PercentAlert, error) {
	out := new(PercentAlert)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/UpdatePercentageAlert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) GetAllPercentageAlerts(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PercentAlertList, error) {
	out := new(PercentAlertList)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/GetAllPercentageAlerts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) HTMLRenderer(ctx context.Context, in *htmlserver.SnippetRequest, opts ...grpc.CallOption) (*htmlserver.SnippetResponse, error) {
	out := new(htmlserver.SnippetResponse)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/HTMLRenderer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PromConfigService service

type PromConfigServiceServer interface {
	// query registry for new targets
	QueryForTargets(context.Context, *Reporter) (*TargetList, error)
	// submit new targes, call this when we want to replace a bunch of new targets
	NewTargets(context.Context, *TargetList) (*common.Void, error)
	// find series by partial name match
	FindSeries(context.Context, *SeriesMatch) (*SeriesList, error)
	// get a list of all metrics
	GetSeries(context.Context, *common.Void) (*SeriesList, error)
	// save or create a simple percentage-based alert. If ID is set it will overwrite existing one
	UpdatePercentageAlert(context.Context, *PercentAlert) (*PercentAlert, error)
	// get all percentage alert
	GetAllPercentageAlerts(context.Context, *common.Void) (*PercentAlertList, error)
	// renderer/editor
	HTMLRenderer(context.Context, *htmlserver.SnippetRequest) (*htmlserver.SnippetResponse, error)
}

func RegisterPromConfigServiceServer(s *grpc.Server, srv PromConfigServiceServer) {
	s.RegisterService(&_PromConfigService_serviceDesc, srv)
}

func _PromConfigService_QueryForTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reporter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).QueryForTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/QueryForTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).QueryForTargets(ctx, req.(*Reporter))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_NewTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).NewTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/NewTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).NewTargets(ctx, req.(*TargetList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_FindSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).FindSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/FindSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).FindSeries(ctx, req.(*SeriesMatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_GetSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).GetSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/GetSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).GetSeries(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_UpdatePercentageAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PercentAlert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).UpdatePercentageAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/UpdatePercentageAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).UpdatePercentageAlert(ctx, req.(*PercentAlert))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_GetAllPercentageAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).GetAllPercentageAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/GetAllPercentageAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).GetAllPercentageAlerts(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_HTMLRenderer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(htmlserver.SnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).HTMLRenderer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/HTMLRenderer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).HTMLRenderer(ctx, req.(*htmlserver.SnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "promconfig.PromConfigService",
	HandlerType: (*PromConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryForTargets",
			Handler:    _PromConfigService_QueryForTargets_Handler,
		},
		{
			MethodName: "NewTargets",
			Handler:    _PromConfigService_NewTargets_Handler,
		},
		{
			MethodName: "FindSeries",
			Handler:    _PromConfigService_FindSeries_Handler,
		},
		{
			MethodName: "GetSeries",
			Handler:    _PromConfigService_GetSeries_Handler,
		},
		{
			MethodName: "UpdatePercentageAlert",
			Handler:    _PromConfigService_UpdatePercentageAlert_Handler,
		},
		{
			MethodName: "GetAllPercentageAlerts",
			Handler:    _PromConfigService_GetAllPercentageAlerts_Handler,
		},
		{
			MethodName: "HTMLRenderer",
			Handler:    _PromConfigService_HTMLRenderer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golang.conradwood.net/apis/promconfig/promconfig.proto",
}

func init() {
	proto.RegisterFile("golang.conradwood.net/apis/promconfig/promconfig.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0x7e, 0x0d, 0x79, 0x1d, 0x18, 0x78, 0xf3, 0xd2, 0x55, 0x9b, 0x52, 0x9a, 0x03, 0xb2, 0x94,
	0x0a, 0x45, 0x15, 0x49, 0x89, 0x54, 0xf5, 0xd0, 0x0f, 0x25, 0x21, 0x5f, 0x6a, 0x02, 0x74, 0x21,
	0x95, 0xd2, 0x9b, 0x6b, 0x0f, 0xc4, 0x92, 0xed, 0x75, 0xd7, 0x4b, 0xd2, 0x5c, 0x7b, 0xea, 0x6f,
	0xe8, 0xb1, 0x3f, 0xaa, 0xbf, 0xa7, 0x62, 0x77, 0x4d, 0x96, 0x04, 0xa2, 0x9c, 0xd8, 0x9d, 0x79,
	0x66, 0xe6, 0x99, 0x79, 0x96, 0x31, 0xbc, 0x1e, 0xb1, 0xd0, 0x8d, 0x47, 0x4d, 0x8f, 0xc5, 0xdc,
	0xf5, 0xaf, 0x18, 0xf3, 0x9b, 0x31, 0x8a, 0x4d, 0x37, 0x09, 0xd2, 0xcd, 0x84, 0xb3, 0xc8, 0x63,
	0xf1, 0x30, 0x18, 0x19, 0xc7, 0x66, 0xc2, 0x99, 0x60, 0x04, 0x6e, 0x2c, 0xb5, 0xe6, 0x3d, 0x39,
	0x3c, 0x16, 0x45, 0x2c, 0xd6, 0x3f, 0x2a, 0xb6, 0x76, 0x5f, 0xcd, 0x0b, 0x11, 0x85, 0x29, 0xf2,
	0x4b, 0xe4, 0xc6, 0x51, 0xc5, 0x39, 0x3f, 0x2d, 0xb0, 0x07, 0x2e, 0x1f, 0xa1, 0x20, 0x04, 0x96,
	0x3a, 0x6e, 0x84, 0x55, 0xab, 0x6e, 0x35, 0x8a, 0x54, 0x9e, 0xc9, 0x1a, 0x14, 0x77, 0x7c, 0x9f,
	0x63, 0x9a, 0x62, 0x5a, 0xcd, 0xd5, 0xf3, 0x8d, 0x22, 0xbd, 0x31, 0x90, 0x2d, 0x28, 0x50, 0x4c,
	0x18, 0x17, 0xc8, 0xab, 0xf9, 0xba, 0xd5, 0x28, 0xb5, 0x1e, 0x37, 0x8d, 0xae, 0x32, 0x1f, 0x9d,
	0xa2, 0x48, 0x0d, 0x0a, 0x47, 0x83, 0x41, 0xaf, 0x1b, 0x87, 0xd7, 0xd5, 0xa5, 0xba, 0xd5, 0x28,
	0xd0, 0xe9, 0xdd, 0x79, 0x01, 0x33, 0xb8, 0x69, 0x66, 0xc5, 0x67, 0x7a, 0x77, 0x42, 0x00, 0xc5,
	0xf8, 0x24, 0x48, 0xc5, 0x0c, 0x07, 0xeb, 0x41, 0x1c, 0x5e, 0xc2, 0xb2, 0x8a, 0x57, 0x1d, 0x95,
	0x5a, 0xc4, 0x0c, 0x50, 0x2e, 0x9a, 0x41, 0x9c, 0xdf, 0x16, 0x94, 0x7b, 0xc8, 0x3d, 0x8c, 0xc5,
	0x4e, 0x88, 0x5c, 0x90, 0x15, 0xc8, 0x1d, 0xb7, 0x65, 0xa9, 0x25, 0x9a, 0x3b, 0x6e, 0x93, 0x3a,
	0x94, 0x06, 0x4c, 0xb8, 0xe1, 0x29, 0x0a, 0x1e, 0x78, 0xd5, 0x9c, 0x64, 0x6b, 0x9a, 0x26, 0x88,
	0x3d, 0x36, 0x8e, 0x85, 0x46, 0xe4, 0x15, 0xc2, 0x30, 0x91, 0xf7, 0xb0, 0xbc, 0x3f, 0x1c, 0xa2,
	0x27, 0x52, 0x39, 0x95, 0x95, 0x56, 0xd5, 0xa4, 0x24, 0xeb, 0x6a, 0xff, 0x2e, 0xfc, 0xfa, 0xf1,
	0xcc, 0x1e, 0x07, 0xb1, 0xd8, 0x6e, 0xd1, 0x2c, 0xc8, 0x39, 0x86, 0x52, 0x1f, 0x79, 0x80, 0xe9,
	0xa9, 0x2b, 0xbc, 0x0b, 0xb2, 0x0a, 0x76, 0x8f, 0xe3, 0x30, 0xf8, 0x5e, 0xb5, 0xa4, 0x64, 0xfa,
	0x46, 0x1c, 0x28, 0xf7, 0x5c, 0x2e, 0x02, 0x37, 0x94, 0x38, 0xc9, 0xb5, 0x40, 0x67, 0x6c, 0xce,
	0x1a, 0xd8, 0x2a, 0xd5, 0xbc, 0xf7, 0xe0, 0xbc, 0x01, 0x50, 0x5e, 0x39, 0xfb, 0x8d, 0x0c, 0x2b,
	0xeb, 0xdc, 0x1a, 0xa4, 0xf2, 0x50, 0x8d, 0x70, 0xda, 0x50, 0x31, 0xc7, 0xa8, 0xb5, 0xb3, 0xe5,
	0x25, 0x8b, 0x9f, 0xe9, 0xda, 0x44, 0x53, 0x8d, 0x73, 0xde, 0x82, 0xbd, 0x27, 0xdd, 0xa4, 0x05,
	0xcb, 0xea, 0x34, 0x37, 0x58, 0xa9, 0xa7, 0x00, 0x34, 0x03, 0x3a, 0x14, 0xca, 0xa6, 0x63, 0x22,
	0x4c, 0x1f, 0xf9, 0x65, 0xe0, 0xa1, 0xd1, 0xa8, 0x69, 0x92, 0x08, 0x37, 0x4a, 0x42, 0x3c, 0x09,
	0xa2, 0x40, 0xc8, 0x81, 0xfd, 0x47, 0x4d, 0xd3, 0xc6, 0x16, 0x94, 0x4d, 0x7d, 0x08, 0x80, 0xdd,
	0xe9, 0xee, 0x76, 0xdb, 0xe7, 0x95, 0x7f, 0x48, 0x11, 0xfe, 0x3d, 0xeb, 0xef, 0xd3, 0x7e, 0xc5,
	0x9a, 0x1c, 0xfb, 0xe7, 0xfd, 0x6e, 0xaf, 0x92, 0x6b, 0xfd, 0xc9, 0xc3, 0xa3, 0x1e, 0x67, 0x91,
	0x22, 0xa1, 0xab, 0x91, 0x0f, 0xf0, 0xff, 0xa7, 0x31, 0xf2, 0xeb, 0x03, 0xc6, 0xf5, 0xd3, 0x23,
	0x73, 0x1f, 0x72, 0x6d, 0xf5, 0x6e, 0x9f, 0x72, 0x98, 0x2d, 0x80, 0x0e, 0x5e, 0x65, 0xb1, 0x0b,
	0x50, 0xb5, 0x72, 0x53, 0xaf, 0x8d, 0xcf, 0x2c, 0xf0, 0xc9, 0x3b, 0x80, 0x83, 0x20, 0xf6, 0xb5,
	0xe0, 0x4f, 0xef, 0xca, 0x27, 0xdf, 0xc4, 0x6c, 0x49, 0x43, 0xff, 0x57, 0x50, 0x3c, 0x44, 0xa1,
	0xa3, 0x67, 0x32, 0x2f, 0x0c, 0xf9, 0x08, 0x4f, 0xce, 0x12, 0xdf, 0x15, 0xa8, 0xe5, 0x75, 0x47,
	0xa8, 0xfe, 0x56, 0x0b, 0xb5, 0xaf, 0x2d, 0xf4, 0x90, 0x36, 0xac, 0x1e, 0xa2, 0xd8, 0x09, 0xc3,
	0x5b, 0xc9, 0x6e, 0x93, 0x59, 0x5b, 0x94, 0x41, 0x52, 0x3a, 0x84, 0xf2, 0xd1, 0xe0, 0xf4, 0x84,
	0x62, 0xec, 0x23, 0x9f, 0xec, 0x9e, 0xa6, 0xb1, 0x25, 0xfb, 0x71, 0x90, 0x24, 0x28, 0x28, 0x7e,
	0x1b, 0x63, 0x2a, 0x6a, 0xcf, 0xe7, 0xfa, 0xd2, 0x84, 0xc5, 0x29, 0xee, 0x76, 0x60, 0x3d, 0x46,
	0x61, 0xae, 0x60, 0xbd, 0x94, 0x27, 0x5b, 0xd8, 0xa0, 0xf0, 0x65, 0xfd, 0x41, 0x1f, 0x88, 0xaf,
	0xb6, 0x5c, 0xd1, 0xdb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x98, 0x3b, 0x02, 0x50, 0x06,
	0x00, 0x00,
}
