// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/promconfig/promconfig.proto
// DO NOT EDIT!

/*
Package promconfig is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/promconfig/promconfig.proto

It has these top-level messages:
	Target
	Reporter
	TargetList
	PercentAlert
	SeriesMatch
	Series
	SeriesList
*/
package promconfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlertEffects int32

const (
	AlertEffects_NOBODY AlertEffects = 0
	AlertEffects_USERS  AlertEffects = 1
	AlertEffects_SYSOP  AlertEffects = 2
)

var AlertEffects_name = map[int32]string{
	0: "NOBODY",
	1: "USERS",
	2: "SYSOP",
}
var AlertEffects_value = map[string]int32{
	"NOBODY": 0,
	"USERS":  1,
	"SYSOP":  2,
}

func (x AlertEffects) String() string {
	return proto.EnumName(AlertEffects_name, int32(x))
}
func (AlertEffects) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Target struct {
	Name      string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Addresses []string  `protobuf:"bytes,2,rep,name=Addresses" json:"Addresses,omitempty"`
	Reporter  *Reporter `protobuf:"bytes,3,opt,name=Reporter" json:"Reporter,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Target) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

type Reporter struct {
	Reporter string `protobuf:"bytes,1,opt,name=Reporter" json:"Reporter,omitempty"`
}

func (m *Reporter) Reset()                    { *m = Reporter{} }
func (m *Reporter) String() string            { return proto.CompactTextString(m) }
func (*Reporter) ProtoMessage()               {}
func (*Reporter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reporter) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

type TargetList struct {
	Reporter *Reporter `protobuf:"bytes,1,opt,name=Reporter" json:"Reporter,omitempty"`
	Targets  []*Target `protobuf:"bytes,2,rep,name=Targets" json:"Targets,omitempty"`
}

func (m *TargetList) Reset()                    { *m = TargetList{} }
func (m *TargetList) String() string            { return proto.CompactTextString(m) }
func (*TargetList) ProtoMessage()               {}
func (*TargetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TargetList) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *TargetList) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type PercentAlert struct {
	ID          uint64       `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TotalMetric string       `protobuf:"bytes,2,opt,name=TotalMetric" json:"TotalMetric,omitempty"`
	CountMetric string       `protobuf:"bytes,3,opt,name=CountMetric" json:"CountMetric,omitempty"`
	Effects     AlertEffects `protobuf:"varint,4,opt,name=Effects,enum=promconfig.AlertEffects" json:"Effects,omitempty"`
}

func (m *PercentAlert) Reset()                    { *m = PercentAlert{} }
func (m *PercentAlert) String() string            { return proto.CompactTextString(m) }
func (*PercentAlert) ProtoMessage()               {}
func (*PercentAlert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PercentAlert) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PercentAlert) GetTotalMetric() string {
	if m != nil {
		return m.TotalMetric
	}
	return ""
}

func (m *PercentAlert) GetCountMetric() string {
	if m != nil {
		return m.CountMetric
	}
	return ""
}

func (m *PercentAlert) GetEffects() AlertEffects {
	if m != nil {
		return m.Effects
	}
	return AlertEffects_NOBODY
}

type SeriesMatch struct {
	Prefix []string `protobuf:"bytes,1,rep,name=Prefix" json:"Prefix,omitempty"`
}

func (m *SeriesMatch) Reset()                    { *m = SeriesMatch{} }
func (m *SeriesMatch) String() string            { return proto.CompactTextString(m) }
func (*SeriesMatch) ProtoMessage()               {}
func (*SeriesMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SeriesMatch) GetPrefix() []string {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type Series struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *Series) Reset()                    { *m = Series{} }
func (m *Series) String() string            { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()               {}
func (*Series) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Series) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SeriesList struct {
	Series []*Series `protobuf:"bytes,1,rep,name=Series" json:"Series,omitempty"`
}

func (m *SeriesList) Reset()                    { *m = SeriesList{} }
func (m *SeriesList) String() string            { return proto.CompactTextString(m) }
func (*SeriesList) ProtoMessage()               {}
func (*SeriesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SeriesList) GetSeries() []*Series {
	if m != nil {
		return m.Series
	}
	return nil
}

func init() {
	proto.RegisterType((*Target)(nil), "promconfig.Target")
	proto.RegisterType((*Reporter)(nil), "promconfig.Reporter")
	proto.RegisterType((*TargetList)(nil), "promconfig.TargetList")
	proto.RegisterType((*PercentAlert)(nil), "promconfig.PercentAlert")
	proto.RegisterType((*SeriesMatch)(nil), "promconfig.SeriesMatch")
	proto.RegisterType((*Series)(nil), "promconfig.Series")
	proto.RegisterType((*SeriesList)(nil), "promconfig.SeriesList")
	proto.RegisterEnum("promconfig.AlertEffects", AlertEffects_name, AlertEffects_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PromConfigService service

type PromConfigServiceClient interface {
	// call this when we want to replace a bunch of new targets
	NewTargets(ctx context.Context, in *TargetList, opts ...grpc.CallOption) (*common.Void, error)
	// get a list of metrics
	GetSeries(ctx context.Context, in *SeriesMatch, opts ...grpc.CallOption) (*SeriesList, error)
}

type promConfigServiceClient struct {
	cc *grpc.ClientConn
}

func NewPromConfigServiceClient(cc *grpc.ClientConn) PromConfigServiceClient {
	return &promConfigServiceClient{cc}
}

func (c *promConfigServiceClient) NewTargets(ctx context.Context, in *TargetList, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/NewTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promConfigServiceClient) GetSeries(ctx context.Context, in *SeriesMatch, opts ...grpc.CallOption) (*SeriesList, error) {
	out := new(SeriesList)
	err := grpc.Invoke(ctx, "/promconfig.PromConfigService/GetSeries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PromConfigService service

type PromConfigServiceServer interface {
	// call this when we want to replace a bunch of new targets
	NewTargets(context.Context, *TargetList) (*common.Void, error)
	// get a list of metrics
	GetSeries(context.Context, *SeriesMatch) (*SeriesList, error)
}

func RegisterPromConfigServiceServer(s *grpc.Server, srv PromConfigServiceServer) {
	s.RegisterService(&_PromConfigService_serviceDesc, srv)
}

func _PromConfigService_NewTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).NewTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/NewTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).NewTargets(ctx, req.(*TargetList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromConfigService_GetSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromConfigServiceServer).GetSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/promconfig.PromConfigService/GetSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromConfigServiceServer).GetSeries(ctx, req.(*SeriesMatch))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "promconfig.PromConfigService",
	HandlerType: (*PromConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTargets",
			Handler:    _PromConfigService_NewTargets_Handler,
		},
		{
			MethodName: "GetSeries",
			Handler:    _PromConfigService_GetSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.conradwood.net/apis/promconfig/promconfig.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/promconfig/promconfig.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0xec, 0xe4, 0x73, 0xf1, 0x24, 0xaa, 0xc2, 0x0a, 0x05, 0x13, 0xf5, 0x60, 0x59, 0x2a,
	0x44, 0x15, 0x72, 0x2a, 0xf7, 0xc2, 0x01, 0x90, 0x9a, 0xa6, 0x42, 0x95, 0x68, 0x12, 0xd9, 0x05,
	0xa9, 0x47, 0x63, 0x4f, 0xc2, 0x4a, 0xf6, 0x6e, 0xb4, 0xde, 0x52, 0xce, 0x48, 0xfc, 0x09, 0x8e,
	0xfc, 0x52, 0xe4, 0xdd, 0x0d, 0x59, 0x08, 0x42, 0x9c, 0x3c, 0x9e, 0xf7, 0xde, 0xcc, 0xf3, 0x8c,
	0x07, 0x5e, 0x6d, 0x04, 0x97, 0xbc, 0x99, 0xac, 0x79, 0x95, 0xb3, 0x75, 0x5c, 0x70, 0x26, 0xf2,
	0xf2, 0x9e, 0xf3, 0x32, 0x66, 0x28, 0x27, 0xf9, 0x86, 0x36, 0x93, 0x8d, 0xe0, 0x75, 0xc1, 0xd9,
	0x8a, 0xae, 0xad, 0x30, 0x56, 0x3a, 0x02, 0xbb, 0xcc, 0x28, 0xfe, 0x4b, 0x8d, 0x82, 0xd7, 0x35,
	0x67, 0xe6, 0xa1, 0xb5, 0x51, 0x05, 0xde, 0x4d, 0x2e, 0xd6, 0x28, 0x09, 0x81, 0xee, 0x3c, 0xaf,
	0x31, 0x70, 0x42, 0x67, 0xec, 0xa7, 0x2a, 0x26, 0x47, 0xe0, 0x9f, 0x97, 0xa5, 0xc0, 0xa6, 0xc1,
	0x26, 0x70, 0xc3, 0xce, 0xd8, 0x4f, 0x77, 0x09, 0x72, 0x0a, 0x0f, 0x52, 0xdc, 0x70, 0x21, 0x51,
	0x04, 0x9d, 0xd0, 0x19, 0xf7, 0x92, 0x47, 0xb1, 0x65, 0x6e, 0x8b, 0xa5, 0x3f, 0x59, 0xd1, 0xd3,
	0x9d, 0x82, 0x8c, 0x2c, 0xb5, 0xee, 0xb9, 0xe3, 0x55, 0x00, 0xda, 0xd5, 0x5b, 0xda, 0xc8, 0x5f,
	0xfa, 0x38, 0xff, 0xd2, 0x87, 0x3c, 0x87, 0x03, 0xad, 0xd7, 0xae, 0x7b, 0x09, 0xb1, 0x05, 0x1a,
	0x4a, 0xb7, 0x94, 0xe8, 0xbb, 0x03, 0xfd, 0x25, 0x8a, 0x02, 0x99, 0x3c, 0xaf, 0x50, 0x48, 0x72,
	0x08, 0xee, 0xd5, 0x4c, 0xb5, 0xea, 0xa6, 0xee, 0xd5, 0x8c, 0x84, 0xd0, 0xbb, 0xe1, 0x32, 0xaf,
	0xae, 0x51, 0x0a, 0x5a, 0x04, 0xae, 0x72, 0x6b, 0xa7, 0x5a, 0xc6, 0x05, 0xbf, 0x63, 0xd2, 0x30,
	0x3a, 0x9a, 0x61, 0xa5, 0xc8, 0x6b, 0x38, 0xb8, 0x5c, 0xad, 0xb0, 0x90, 0x4d, 0xd0, 0x0d, 0x9d,
	0xf1, 0x61, 0x12, 0xd8, 0x96, 0x54, 0x5f, 0x83, 0x4f, 0xe1, 0xdb, 0x97, 0x27, 0xde, 0x1d, 0x65,
	0xf2, 0x2c, 0x49, 0xb7, 0xa2, 0xe8, 0x18, 0x7a, 0x19, 0x0a, 0x8a, 0xcd, 0x75, 0x2e, 0x8b, 0x8f,
	0x64, 0x08, 0xde, 0x52, 0xe0, 0x8a, 0x7e, 0x0e, 0x1c, 0xb5, 0x16, 0xf3, 0x16, 0x1d, 0x81, 0xa7,
	0x69, 0x7f, 0xda, 0x67, 0xf4, 0x02, 0x40, 0xa3, 0x6a, 0xae, 0x27, 0x5b, 0xae, 0xaa, 0xf1, 0xdb,
	0x90, 0x34, 0x92, 0x1a, 0xc6, 0xc9, 0x29, 0xf4, 0x6d, 0x8f, 0x04, 0xc0, 0x9b, 0x2f, 0xa6, 0x8b,
	0xd9, 0xed, 0xe0, 0x3f, 0xe2, 0xc3, 0xff, 0xef, 0xb2, 0xcb, 0x34, 0x1b, 0x38, 0x6d, 0x98, 0xdd,
	0x66, 0x8b, 0xe5, 0xc0, 0x4d, 0xbe, 0x3a, 0xf0, 0x70, 0x29, 0x78, 0x7d, 0xa1, 0xea, 0x65, 0x28,
	0x3e, 0xd1, 0x02, 0x49, 0x02, 0x30, 0xc7, 0x7b, 0x33, 0x79, 0x32, 0xdc, 0x5f, 0x4b, 0xeb, 0x6c,
	0xd4, 0x8f, 0xcd, 0x4f, 0xfa, 0x9e, 0xd3, 0x92, 0xbc, 0x04, 0xff, 0x0d, 0x4a, 0xf3, 0x59, 0x8f,
	0xf7, 0x4d, 0xaa, 0x89, 0x8c, 0x86, 0xfb, 0x40, 0x5b, 0x6b, 0xfa, 0x0c, 0x8e, 0x19, 0x4a, 0xfb,
	0x20, 0xcc, 0x89, 0xb4, 0x37, 0x61, 0x69, 0x3e, 0x78, 0xea, 0x22, 0xce, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x3b, 0xc6, 0xc8, 0x6a, 0x8e, 0x03, 0x00, 0x00,
}
